version: '3'
services:
  tomcat:
    image: tomcat:10-jre11-openjdk-slim
    ports:
     - "8080:8080"
    volumes:
      - ./target/JakartaWebStarter-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/JakartaWebStarter-1.0-SNAPSHOT.war